version: 2
<<<<<<< HEAD
<<<<<<< HEAD
=======
registries:
  npm-abaco-github:
    type: npm-registry
    url: https://npm.pkg.github.com/Abaco-Technol
    token: ${{secrets.ABACO_GITHUB_PACKAGES_TOKEN}}

>>>>>>> origin/main
updates:
  - package-ecosystem: "npm"
=======

updates:
  - &default_settings
    package-ecosystem: "npm"
>>>>>>> origin/main
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
<<<<<<< HEAD
<<<<<<< HEAD
=======
    assignees:
      - "codex"
>>>>>>> origin/main
    groups:
      minor-and-patch:
        update-types: ["minor", "patch"]
    registries:
      - npm-abaco-github

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    assignees:
      - "codex"
    groups:
      minor-and-patch:
        update-types: ["minor", "patch"]
<<<<<<< HEAD
=======

>>>>>>> origin/main
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    assignees:
      - "codex"
    groups:
      minor-and-patch:
        update-types: ["minor", "patch"]
<<<<<<< HEAD
=======

>>>>>>> origin/main
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
=======
    assignees:
      - "codex"
    reviewers:
      - "sonarqube"
      - "coderabbit"
      - "sourcery"
    groups:
      minor-and-patch:
        update-types: ["minor", "patch"]
  - <<: *default_settings
    package-ecosystem: "pip"
    open-pull-requests-limit: 10
  - <<: *default_settings
    package-ecosystem: "github-actions"
>>>>>>> origin/main
    open-pull-requests-limit: 5
    assignees:
      - "codex"
    reviewers:
      - "sonarqube"
      - "coderabbit"
      - "sourcery"
    groups:
      minor-and-patch:
        update-types: ["minor", "patch"]
