name: CI Analytics

on:
  push:
    paths:
      - "apps/analytics/**"

jobs:
  analytics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ad675ce3f5cc7d71d4c5396b0ec8dadd6f39f110
      - uses: actions/setup-python@270fb6bdc8d81da4cc4b67f3f276f0b0d496e7f3
        with:
          python-version: "3.11"
      - name: Install
        run: |
          cd apps/analytics
          pip install -r requirements.txt
      - name: Validate
        run: |
          cd apps/analytics
          python -c "import pandas as pd; print('Environment ready. Pandas version:', pd.__version__)"
